### PR TITLE
Fix PHP 7 compatibility & add unit test

### PR DESCRIPTION
**Pull request by davidcochrum**

### CODE REVIEW

**Comment by motdotla** [comment]
Wow @davidcochrum, this is an incredible PR!

I'm hesitant to split the cli into other libraries though (outside the command line cli) because then they could start diverging from each other.

As a php dev what are your thoughts?

Did you know you could also install via homebrew rather than using npx? https://www.dotenv.org/install/

**Comment by davidcochrum** [comment]
I don't mind maintaining parity between the PHP and Node CLIs ... I don't anticipate them changing all that much anyhow ... I'm working on projects that don't have any other need for Node and my goal was to avoid installing it just for managing envs

**Comment by davidcochrum** [comment]
I think I just realized that I don't need the CLI in any environment besides dev machines ... is that correct?

**Comment by motdotla** [comment]
Hi @davidcochrum, sorry to do this to you but I am going to close this.

I made a slew of updates yesterday to fix this library up.

For any changes you would still like to add, could you re-add them under a separate PR. There are too many conflicts here to make it worthwhile. Sorry again for throwing out your hard work like this.

**Comment by motdotla** [comment]
@davidcochrum I put together a Laravel guide here:

https://www.dotenv.org/docs/frameworks/laravel/heroku

But I also noticed you started building a Laravel package here:

https://gitlab.com/davidcochrum/dotenv-vault-laravel

Would you mind updating that to the latest phpdotenv-vault `v0.2.x`. Then I'd like to update our Laravel docs to use your plugin.

Also, would you consider hosting that code on GitHub instead of GitLab? We find the community can engage better over GitHub for PRs, comments, etc.

**Comment by davidcochrum** [comment]
Updated and released v1.1.0
https://gitlab.com/davidcochrum/dotenv-vault-laravel/-/releases/v1.1.0

I have GitLab mirroring to GitHub so any community discussion/contribution will be synced

**Comment by motdotla** [comment]
I'll work on updating our guides to use your Laravel plugin this evening!

Also could you take a look at this:

https://www.dotenv.org/blog/2023/11/07/phpdotenv-is-inconsistent-across-development-and-production.html

As a more experienced php dev than me, I'd like your take.

**Comment by davidcochrum** [comment]
There's a whole [paragraph in the phpdotenv README](https://github.com/vlucas/phpdotenv#putenv-and-getenv) about thread safety with `getenv()`  and `putenv()`

In my experience, most devs don't interact with this library directly, but instead do so indirectly via their framework of choice. [Laravel uses the library](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Foundation/Bootstrap/LoadEnvironmentVariables.php#L28) with `safeLoad()` and its own configured repositories.

[Symfony uses its own library](https://github.com/symfony/dotenv) that behaves a bit differently and is completely independent from phpdotenv

**Comment by motdotla** [comment]
Symfony's implementation looks more sane.

**Pull request closed without merging**
